FROM python:3.9-slim

WORKDIR /app

COPY be/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY be/ .

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
