services:
  be:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

  fe:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    volumes:
      - ./fe:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - PYTHON_BACKEND_URL=http://be:8000
